name: Python Practice Workflow

on:
  push:
    branches: [main]

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have requirements.txt, uncomment below
          # pip install -r requirements.txt

      - name: Run a Python script
        run: |
          echo 'print("🐍 Hello from Python in GitHub Actions!")' > hello.py
          python hello.py
